# Importing Libraries

In [96]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

# CROSS-VALIDATION library(train test Split library)
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

from sklearn.metrics import r2_score,mean_squared_error, mean_absolute_error

import pickle

# removing the warning
import warnings
warnings.filterwarnings('ignore')

# Initializing Label Encoder

In [97]:
le = LabelEncoder()

# Reading Dataset

In [98]:
df = pd.read_csv("Bus Fare.csv")
df.head()

            Bus Name   Passanger Age  Distance Travel(km)  Bus fare
0              V.I.P              17                   22        30
1             Bolaka              34                   25        60
2  Gajipur Poribohon              19                   32        75
3             United              23                   30        80
4             Bolaka              17                   17        20

Making copy to work on the copied dataset.

In [99]:
df1 = df.copy()

# Initial Analysis

In [100]:
df1.isna().sum()

Bus Name               0
 Passanger Age         0
Distance Travel(km)    0
Bus fare               0
dtype: int64

In [101]:
df1.duplicated().sum()

np.int64(0)

In [102]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Bus Name             24 non-null     str
 1    Passanger Age       24 non-null     int64
 2   Distance Travel(km)  24 non-null     int64
 3   Bus fare             24 non-null     int64
dtypes: int64(3), str(1)
memory usage: 900.0 bytes

# Encoding a column

In [103]:
df1['Bus_Name_Encoded'] = le.fit_transform(df1['Bus Name'])

In [104]:
df1.head()

,Bus Name,Passanger Age,Distance Travel(km),Bus fare,Bus_Name_Encoded
0,V.I.P,17,22,30,5
1,Bolaka,34,25,60,0
2,Gajipur Poribohon,19,32,75,1
3,United,23,30,80,4
4,Bolaka,17,17,20,0

# Renaming The columns

In [105]:
df1 = df1.rename(columns={"Bus Name":"Bus_Name", "Passenger Age":"Passenger_Age", "Distance Travel(km)":"Distance_Travelled", "Bus fare":"Bus_Fare"})

In [106]:
df1.head()

,Bus_Name,Passanger Age,Distance_Travelled,Bus_Fare,Bus_Name_Encoded
0,V.I.P,17,22,30,5
1,Bolaka,34,25,60,0
2,Gajipur Poribohon,19,32,75,1
3,United,23,30,80,4
4,Bolaka,17,17,20,0

In [107]:
df1 = df1.rename(columns={"Bus_Name_Encoded":"Bus_Name_Encoded", "Passenger_Age":"Passenger_Age", "Distance_Travelled":"Distance_Travelled", "Bus_Fare":"Bus_Fare"})

In [108]:
df1.head()

,Bus_Name,Passanger Age,Distance_Travelled,Bus_Fare,Bus_Name_Encoded
0,V.I.P,17,22,30,5
1,Bolaka,34,25,60,0
2,Gajipur Poribohon,19,32,75,1
3,United,23,30,80,4
4,Bolaka,17,17,20,0

# Separating the dataset

In [109]:
df1.columns

Index(['Bus_Name', ' Passanger Age', 'Distance_Travelled', 'Bus_Fare',
       'Bus_Name_Encoded'],
      dtype='str')

In [110]:
x =df1[["Bus_Name_Encoded", " Passanger Age", "Distance_Travelled"]]
y = df1[["Bus_Fare"]]

# Split dataset for training-testing

In [111]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = .2, random_state = 42)

In [112]:
xtrain.shape, xtest.shape, ytrain.shape, ytest.shape

((19, 3), (5, 3), (19, 1), (5, 1))

# Model Train

In [113]:
lr = LinearRegression()

In [114]:
model = lr.fit(xtrain, ytrain)

R2 score for train data

In [115]:
model.score(xtrain, ytrain)

0.5839704970103679

Check Test Result

In [116]:
model.score(xtest, ytest)

0.685093698150221

In [117]:
df1.head(3)

,Bus_Name,Passanger Age,Distance_Travelled,Bus_Fare,Bus_Name_Encoded
0,V.I.P,17,22,30,5
1,Bolaka,34,25,60,0
2,Gajipur Poribohon,19,32,75,1

# Checking Prediction

In [118]:
model.predict([[5, 25, 50]])

array([[110.81804671]])

# Evaluate the Model

In [119]:
y_pred = model.predict(xtest)
y_pred

array([[68.66029306],
       [27.01601798],
       [50.64829049],
       [50.60236623],
       [79.95580073]])

In [120]:
ytest

    Bus_Fare
8         60
16        35
0         30
18        45
11       100

In [121]:
df1['error'] = ytest - y_pred

In [122]:
y_Fair = model.predict(x)

In [123]:
df1['error_total'] = y - y_Fair

In [124]:
df1.head(10)

,Bus_Name,Passanger Age,Distance_Travelled,Bus_Fare,Bus_Name_Encoded,error,error_total
0,V.I.P,17,22,30,5,-20.648290,-20.648290
1,Bolaka,34,25,60,0,NaN,-1.966887
2,Gajipur Poribohon,19,32,75,1,NaN,11.210380
3,United,23,30,80,4,NaN,10.754094
4,Bolaka,17,17,20,0,NaN,-11.691815
5,Gajipur Poribohon,40,24,60,1,NaN,-7.303554
6,V.I.P,27,16,45,5,NaN,-3.170931
7,Tawqa,18,15,45,3,NaN,10.519451
8,Provati,33,27,60,2,-8.660293,-8.660293
9,V.I.P,22,40,90,5,NaN,0.798178

In [125]:
df1.drop(['error'], axis=1)

,Bus_Name,Passanger Age,Distance_Travelled,Bus_Fare,Bus_Name_Encoded,error_total
0,V.I.P,17,22,30,5,-20.648290
1,Bolaka,34,25,60,0,-1.966887
2,Gajipur Poribohon,19,32,75,1,11.210380
3,United,23,30,80,4,10.754094
4,Bolaka,17,17,20,0,-11.691815
5,Gajipur Poribohon,40,24,60,1,-7.303554
6,V.I.P,27,16,45,5,-3.170931
7,Tawqa,18,15,45,3,10.519451
8,Provati,33,27,60,2,-8.660293
9,V.I.P,22,40,90,5,0.798178
10,United,25,25,60,4,-1.549939
11,Provati,18,40,100,2,20.044199
12,Tawqa,15,24,60,3,11.133200
13,Gajipur Poribohon,15,17,20,1,-11.809875
14,Bolaka,18,32,80,0,18.995992
15,V.I.P,14,35,40,5,-32.614011
16,Provati,16,13,35,2,7.983982
17,United,17,40,90,4,7.140528
18,Tawqa,34,16,45,3,-5.602366
19,Bolaka,15,36,40,0,-25.915923
20,Provati,15,30,80,2,21.660424
21,Tawqa,17,28,60,3,1.775362
22,Gajipur Poribohon,30,32,75,1,1.429352
23,United,15,18,40,4,0.605975

In [126]:
r_score = r2_score(ytest, y_pred)
r_score

0.685093698150221

In [ ]:
# pred with user input
bus_name_encoded = float(input("Enter Bus Name Encoded value: "))
passanger_age = float(input("Enter Passanger Age: "))
distance_travelled = float(input("Enter Distance Travelled: "))

test_data = [[bus_name_encoded, passanger_age, distance_travelled]]
prediction = model.predict(test_data)

print(f"Predicted Bus Fare: {prediction[0][0]}")

# Cost of the Model

In [ ]:
# cost of the model
mse = mean_squared_error(ytest, y_pred)
mse

425.5334286220691