# Dictionary

In [1]:
dic = {
  "name" : "hello",
  "age" : 13
}

dic

{'name': 'hello', 'age': 13}

In [3]:
dic = {
  "name" : ["hello", "Hi"],
  "age" : [13, 12]
}

dic

{'name': ['hello', 'Hi'], 'age': [13, 12]}

In [4]:
dic["pro"] = 'python'
dic

{'name': ['hello', 'Hi'], 'age': [13, 12], 'pro': 'python'}

In [5]:
dic["pros"] = ['python', "pycharm"]
dic

{'name': ['hello', 'Hi'],
 'age': [13, 12],
 'pro': 'python',
 'pros': ['python', 'pycharm']}

In [6]:
dic.keys()

dict_keys(['name', 'age', 'pro', 'pros'])

In [7]:
dic.values()

dict_values([['hello', 'Hi'], [13, 12], 'python', ['python', 'pycharm']])

In [8]:
dic["name"]

['hello', 'Hi']

In [22]:
dic = {
  "name" : ["hello", "Hi"],
  "age" : [13, 12],
  
  'car' :{"car_name" : ['corola', 'toyota'],
   "model" : ['A', 'B']}
}

dic

{'name': ['hello', 'Hi'],
 'age': [13, 12],
 'car': {'car_name': ['corola', 'toyota'], 'model': ['A', 'B']}}

In [10]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']

In [5]:
pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
     ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
     --------------------------------------- 0.0/11.3 MB 960.0 kB/s eta 0:00:12
     ---------------------------------------- 0.1/11.3 MB 2.2 MB/s eta 0:00:06
      --------------------------------------- 0.2/11.3 MB 2.0 MB/s eta 0:00:06
     - -------------------------------------- 0.5/11.3 MB 2.9 MB/s eta 0:00:04
     - -------------------------------------- 0.6/11.3 MB 2.5 MB/s eta 0:00:05
     -- ------------------------------------- 0.6/11.3 MB 2.6 MB/s eta 0:00:05
     -- ------------------------------------- 0.6/11.3 MB 2.6 MB/s eta 0:00:05
     -- ------------------------------------- 0.6/11.3 MB 1.7 MB/s eta 0:00:07
     -- ------------------------------------- 0.7/11.3 MB 1.7 MB/s eta 0:00:07
     -- ------------------------------------- 0.7/11.3 MB 1.7 MB/s eta 0:00:07
     -- ------------------------------------- 0.7/11.3 MB 1.7 MB/s eta 0:00:07
     -- ------------------------------------- 0.8/11.3 MB 1.4 MB/s eta 0:00:08
     --- ------------------------------------ 0.9/11.3 MB 1.4 MB/s eta 0:00:08
     --- ------------------------------------ 1.0/11.3 MB 1.6 MB/s eta 0:00:07
     --- ------------------------------------ 1.0/11.3 MB 1.6 MB/s eta 0:00:07
     --- ------------------------------------ 1.0/11.3 MB 1.6 MB/s eta 0:00:07
     ---- ----------------------------------- 1.1/11.3 MB 1.5 MB/s eta 0:00:08
     ---- ----------------------------------- 1.1/11.3 MB 1.5 MB/s eta 0:00:08
     ---- ----------------------------------- 1.1/11.3 MB 1.5 MB/s eta 0:00:08
     ---- ----------------------------------- 1.3/11.3 MB 1.5 MB/s eta 0:00:07
     ---- ----------------------------------- 1.4/11.3 MB 1.4 MB/s eta 0:00:07
     ----- ---------------------------------- 1.5/11.3 MB 1.5 MB/s eta 0:00:07
     ----- ---------------------------------- 1.6/11.3 MB 1.5 MB/s eta 0:00:07
     ----- ---------------------------------- 1.6/11.3 MB 1.5 MB/s eta 0:00:07
     ----- ---------------------------------- 1.7/11.3 MB 1.5 MB/s eta 0:00:07
     ------ --------------------------------- 1.8/11.3 MB 1.5 MB/s eta 0:00:07
     ------ --------------------------------- 1.8/11.3 MB 1.4 MB/s eta 0:00:07
     ------ --------------------------------- 1.9/11.3 MB 1.4 MB/s eta 0:00:07
     ------ --------------------------------- 1.9/11.3 MB 1.4 MB/s eta 0:00:07
     ------- -------------------------------- 2.0/11.3 MB 1.4 MB/s eta 0:00:07
     ------- -------------------------------- 2.0/11.3 MB 1.4 MB/s eta 0:00:07
     ------- -------------------------------- 2.1/11.3 MB 1.4 MB/s eta 0:00:07
     ------- -------------------------------- 2.2/11.3 MB 1.4 MB/s eta 0:00:07
     ------- -------------------------------- 2.2/11.3 MB 1.4 MB/s eta 0:00:07
     -------- ------------------------------- 2.3/11.3 MB 1.4 MB/s eta 0:00:07
     -------- ------------------------------- 2.3/11.3 MB 1.4 MB/s eta 0:00:07
     -------- ------------------------------- 2.4/11.3 MB 1.4 MB/s eta 0:00:07
     -------- ------------------------------- 2.4/11.3 MB 1.4 MB/s eta 0:00:07
     -------- ------------------------------- 2.5/11.3 MB 1.4 MB/s eta 0:00:07
     -------- ------------------------------- 2.5/11.3 MB 1.4 MB/s eta 0:00:07
     --------- ------------------------------ 2.6/11.3 MB 1.4 MB/s eta 0:00:07
     --------- ------------------------------ 2.7/11.3 MB 1.4 MB/s eta 0:00:07
     --------- ------------------------------ 2.7/11.3 MB 1.4 MB/s eta 0:00:07
     --------- ------------------------------ 2.8/11.3 MB 1.4 MB/s eta 0:00:07
     --------- ------------------------------ 2.8/11.3 MB 1.4 MB/s eta 0:00:07
     ---------- ----------------------------- 2.9/11.3 MB 1.3 MB/s eta 0:00:07
     ---------- ----------------------------- 2.9/11.3 MB 1.4 MB/s eta 0:00:07
     ---------- ----------------------------- 3.0/11.3 MB 1.3 MB/s eta 0:00:07
     ---------- ----------------------------- 3.1/11.3 MB 1.3 MB/s eta 0:00:07
     ---------- ----------------------------- 3.1/11.3 MB 1.3 MB/s eta 0:00:07
     ----------- ---------------------------- 3.2/11.3 MB 1.3 MB/s eta 0:00:07
     ----------- ---------------------------- 3.2/11.3 MB 1.3 MB/s eta 0:00:07
     ----------- ---------------------------- 3.3/11.3 MB 1.3 MB/s eta 0:00:07
     ----------- ---------------------------- 3.4/11.3 MB 1.3 MB/s eta 0:00:07
     ------------ --------------------------- 3.4/11.3 MB 1.3 MB/s eta 0:00:06
     ------------ --------------------------- 3.5/11.3 MB 1.3 MB/s eta 0:00:06
     ------------ --------------------------- 3.5/11.3 MB 1.3 MB/s eta 0:00:06
     ------------ --------------------------- 3.6/11.3 MB 1.3 MB/s eta 0:00:06
     ------------ --------------------------- 3.6/11.3 MB 1.3 MB/s eta 0:00:06
     ------------ --------------------------- 3.7/11.3 MB 1.3 MB/s eta 0:00:06
     ------------- -------------------------- 3.8/11.3 MB 1.3 MB/s eta 0:00:06
     ------------- -------------------------- 3.8/11.3 MB 1.3 MB/s eta 0:00:06
     ------------- -------------------------- 3.9/11.3 MB 1.3 MB/s eta 0:00:06
     ------------- -------------------------- 3.9/11.3 MB 1.3 MB/s eta 0:00:06
     -------------- ------------------------- 4.0/11.3 MB 1.3 MB/s eta 0:00:06
     -------------- ------------------------- 4.0/11.3 MB 1.3 MB/s eta 0:00:06
     -------------- ------------------------- 4.1/11.3 MB 1.3 MB/s eta 0:00:06
     -------------- ------------------------- 4.2/11.3 MB 1.3 MB/s eta 0:00:06
     -------------- ------------------------- 4.2/11.3 MB 1.3 MB/s eta 0:00:06
     --------------- ------------------------ 4.3/11.3 MB 1.3 MB/s eta 0:00:06
     --------------- ------------------------ 4.3/11.3 MB 1.3 MB/s eta 0:00:06
     --------------- ------------------------ 4.4/11.3 MB 1.3 MB/s eta 0:00:06
     --------------- ------------------------ 4.4/11.3 MB 1.3 MB/s eta 0:00:06
     --------------- ------------------------ 4.5/11.3 MB 1.3 MB/s eta 0:00:06
     ---------------- ----------------------- 4.5/11.3 MB 1.3 MB/s eta 0:00:06
     ---------------- ----------------------- 4.6/11.3 MB 1.3 MB/s eta 0:00:06
     ---------------- ----------------------- 4.7/11.3 MB 1.3 MB/s eta 0:00:06
     ---------------- ----------------------- 4.7/11.3 MB 1.3 MB/s eta 0:00:06
     ---------------- ----------------------- 4.7/11.3 MB 1.3 MB/s eta 0:00:06
     ----------------- ---------------------- 4.8/11.3 MB 1.3 MB/s eta 0:00:06
     ----------------- ---------------------- 4.9/11.3 MB 1.3 MB/s eta 0:00:05
     ----------------- ---------------------- 4.9/11.3 MB 1.3 MB/s eta 0:00:05
     ----------------- ---------------------- 5.0/11.3 MB 1.3 MB/s eta 0:00:05
     ----------------- ---------------------- 5.1/11.3 MB 1.3 MB/s eta 0:00:05
     ------------------ --------------------- 5.1/11.3 MB 1.3 MB/s eta 0:00:05
     ------------------ --------------------- 5.2/11.3 MB 1.3 MB/s eta 0:00:05
     ------------------ --------------------- 5.2/11.3 MB 1.3 MB/s eta 0:00:05
     ------------------ --------------------- 5.3/11.3 MB 1.3 MB/s eta 0:00:05
     ------------------ --------------------- 5.3/11.3 MB 1.3 MB/s eta 0:00:05
     ------------------- -------------------- 5.4/11.3 MB 1.3 MB/s eta 0:00:05
     ------------------- -------------------- 5.5/11.3 MB 1.3 MB/s eta 0:00:05
     ------------------- -------------------- 5.5/11.3 MB 1.3 MB/s eta 0:00:05
     ------------------- -------------------- 5.6/11.3 MB 1.3 MB/s eta 0:00:05
     ------------------- -------------------- 5.6/11.3 MB 1.3 MB/s eta 0:00:05
     -------------------- ------------------- 5.7/11.3 MB 1.3 MB/s eta 0:00:05
     -------------------- ------------------- 5.7/11.3 MB 1.3 MB/s eta 0:00:05
     -------------------- ------------------- 5.8/11.3 MB 1.3 MB/s eta 0:00:05
     -------------------- ------------------- 5.9/11.3 MB 1.3 MB/s eta 0:00:05
     -------------------- ------------------- 5.9/11.3 MB 1.3 MB/s eta 0:00:05
     --------------------- ------------------ 6.0/11.3 MB 1.3 MB/s eta 0:00:05
     --------------------- ------------------ 6.0/11.3 MB 1.3 MB/s eta 0:00:05
     --------------------- ------------------ 6.1/11.3 MB 1.3 MB/s eta 0:00:05
     --------------------- ------------------ 6.1/11.3 MB 1.3 MB/s eta 0:00:05
     --------------------- ------------------ 6.2/11.3 MB 1.3 MB/s eta 0:00:05
     ---------------------- ----------------- 6.3/11.3 MB 1.3 MB/s eta 0:00:04
     ---------------------- ----------------- 6.3/11.3 MB 1.3 MB/s eta 0:00:04
     ---------------------- ----------------- 6.4/11.3 MB 1.3 MB/s eta 0:00:04
     ---------------------- ----------------- 6.4/11.3 MB 1.3 MB/s eta 0:00:04
     ---------------------- ----------------- 6.5/11.3 MB 1.3 MB/s eta 0:00:04
     ----------------------- ---------------- 6.5/11.3 MB 1.3 MB/s eta 0:00:04
     ----------------------- ---------------- 6.6/11.3 MB 1.3 MB/s eta 0:00:04
     ----------------------- ---------------- 6.7/11.3 MB 1.3 MB/s eta 0:00:04
     ----------------------- ---------------- 6.7/11.3 MB 1.3 MB/s eta 0:00:04
     ----------------------- ---------------- 6.8/11.3 MB 1.3 MB/s eta 0:00:04
     ------------------------ --------------- 6.8/11.3 MB 1.3 MB/s eta 0:00:04
     ------------------------ --------------- 6.9/11.3 MB 1.3 MB/s eta 0:00:04
     ------------------------ --------------- 6.9/11.3 MB 1.3 MB/s eta 0:00:04
     ------------------------ --------------- 7.0/11.3 MB 1.3 MB/s eta 0:00:04
     ------------------------ --------------- 7.1/11.3 MB 1.3 MB/s eta 0:00:04
     ------------------------- -------------- 7.1/11.3 MB 1.3 MB/s eta 0:00:04
     ------------------------- -------------- 7.2/11.3 MB 1.3 MB/s eta 0:00:04
     ------------------------- -------------- 7.2/11.3 MB 1.3 MB/s eta 0:00:04
     ------------------------- -------------- 7.3/11.3 MB 1.3 MB/s eta 0:00:04
     ------------------------- -------------- 7.3/11.3 MB 1.3 MB/s eta 0:00:04
     -------------------------- ------------- 7.4/11.3 MB 1.3 MB/s eta 0:00:04
     -------------------------- ------------- 7.4/11.3 MB 1.3 MB/s eta 0:00:04
     -------------------------- ------------- 7.5/11.3 MB 1.3 MB/s eta 0:00:04
     -------------------------- ------------- 7.6/11.3 MB 1.3 MB/s eta 0:00:03
     -------------------------- ------------- 7.6/11.3 MB 1.3 MB/s eta 0:00:03
     --------------------------- ------------ 7.7/11.3 MB 1.3 MB/s eta 0:00:03
     --------------------------- ------------ 7.7/11.3 MB 1.3 MB/s eta 0:00:03
     --------------------------- ------------ 7.8/11.3 MB 1.3 MB/s eta 0:00:03
     --------------------------- ------------ 7.8/11.3 MB 1.3 MB/s eta 0:00:03
     --------------------------- ------------ 7.9/11.3 MB 1.3 MB/s eta 0:00:03
     ---------------------------- ----------- 8.0/11.3 MB 1.3 MB/s eta 0:00:03
     ---------------------------- ----------- 8.0/11.3 MB 1.3 MB/s eta 0:00:03
     ---------------------------- ----------- 8.0/11.3 MB 1.3 MB/s eta 0:00:03
     ---------------------------- ----------- 8.0/11.3 MB 1.3 MB/s eta 0:00:03
     ---------------------------- ----------- 8.2/11.3 MB 1.3 MB/s eta 0:00:03
     ----------------------------- ---------- 8.2/11.3 MB 1.3 MB/s eta 0:00:03
     ----------------------------- ---------- 8.3/11.3 MB 1.3 MB/s eta 0:00:03
     ----------------------------- ---------- 8.4/11.3 MB 1.3 MB/s eta 0:00:03
     ----------------------------- ---------- 8.4/11.3 MB 1.3 MB/s eta 0:00:03
     ----------------------------- ---------- 8.5/11.3 MB 1.3 MB/s eta 0:00:03
     ------------------------------ --------- 8.5/11.3 MB 1.3 MB/s eta 0:00:03
     ------------------------------ --------- 8.6/11.3 MB 1.3 MB/s eta 0:00:03
     ------------------------------ --------- 8.7/11.3 MB 1.3 MB/s eta 0:00:03
     ------------------------------ --------- 8.7/11.3 MB 1.3 MB/s eta 0:00:03
     ------------------------------ --------- 8.8/11.3 MB 1.3 MB/s eta 0:00:03
     ------------------------------- -------- 8.8/11.3 MB 1.3 MB/s eta 0:00:03
     ------------------------------- -------- 8.9/11.3 MB 1.3 MB/s eta 0:00:02
     ------------------------------- -------- 8.9/11.3 MB 1.3 MB/s eta 0:00:02
     ------------------------------- -------- 9.0/11.3 MB 1.3 MB/s eta 0:00:02
     ------------------------------- -------- 9.1/11.3 MB 1.3 MB/s eta 0:00:02
     -------------------------------- ------- 9.1/11.3 MB 1.3 MB/s eta 0:00:02
     -------------------------------- ------- 9.2/11.3 MB 1.3 MB/s eta 0:00:02
     -------------------------------- ------- 9.2/11.3 MB 1.3 MB/s eta 0:00:02
     -------------------------------- ------- 9.3/11.3 MB 1.3 MB/s eta 0:00:02
     -------------------------------- ------- 9.3/11.3 MB 1.3 MB/s eta 0:00:02
     --------------------------------- ------ 9.4/11.3 MB 1.3 MB/s eta 0:00:02
     --------------------------------- ------ 9.5/11.3 MB 1.3 MB/s eta 0:00:02
     --------------------------------- ------ 9.5/11.3 MB 1.3 MB/s eta 0:00:02
     --------------------------------- ------ 9.6/11.3 MB 1.3 MB/s eta 0:00:02
     --------------------------------- ------ 9.6/11.3 MB 1.3 MB/s eta 0:00:02
     ---------------------------------- ----- 9.7/11.3 MB 1.3 MB/s eta 0:00:02
     ---------------------------------- ----- 9.7/11.3 MB 1.3 MB/s eta 0:00:02
     ---------------------------------- ----- 9.8/11.3 MB 1.3 MB/s eta 0:00:02
     ---------------------------------- ----- 9.8/11.3 MB 1.3 MB/s eta 0:00:02
     ---------------------------------- ----- 9.9/11.3 MB 1.3 MB/s eta 0:00:02
     ----------------------------------- ---- 10.0/11.3 MB 1.3 MB/s eta 0:00:02
     ----------------------------------- ---- 10.0/11.3 MB 1.3 MB/s eta 0:00:02
     ----------------------------------- ---- 10.1/11.3 MB 1.3 MB/s eta 0:00:02
     ----------------------------------- ---- 10.1/11.3 MB 1.2 MB/s eta 0:00:01
     ----------------------------------- ---- 10.2/11.3 MB 1.3 MB/s eta 0:00:01
     ------------------------------------ --- 10.3/11.3 MB 1.3 MB/s eta 0:00:01
     ------------------------------------ --- 10.3/11.3 MB 1.2 MB/s eta 0:00:01
     ------------------------------------ --- 10.4/11.3 MB 1.2 MB/s eta 0:00:01
     ------------------------------------ --- 10.4/11.3 MB 1.2 MB/s eta 0:00:01
     ------------------------------------ --- 10.5/11.3 MB 1.2 MB/s eta 0:00:01
     ------------------------------------- -- 10.6/11.3 MB 1.2 MB/s eta 0:00:01
     ------------------------------------- -- 10.6/11.3 MB 1.2 MB/s eta 0:00:01
     ------------------------------------- -- 10.7/11.3 MB 1.2 MB/s eta 0:00:01
     ------------------------------------- -- 10.7/11.3 MB 1.2 MB/s eta 0:00:01
     ------------------------------------- -- 10.8/11.3 MB 1.2 MB/s eta 0:00:01
     -------------------------------------- - 10.8/11.3 MB 1.2 MB/s eta 0:00:01
     -------------------------------------- - 10.9/11.3 MB 1.2 MB/s eta 0:00:01
     -------------------------------------- - 10.9/11.3 MB 1.2 MB/s eta 0:00:01
     -------------------------------------- - 11.0/11.3 MB 1.2 MB/s eta 0:00:01
     -------------------------------------- - 11.1/11.3 MB 1.2 MB/s eta 0:00:01
     ---------------------------------------  11.1/11.3 MB 1.2 MB/s eta 0:00:01
     ---------------------------------------  11.2/11.3 MB 1.2 MB/s eta 0:00:01
     ---------------------------------------  11.2/11.3 MB 1.2 MB/s eta 0:00:01
     ---------------------------------------  11.3/11.3 MB 1.2 MB/s eta 0:00:01
     ---------------------------------------  11.3/11.3 MB 1.2 MB/s eta 0:00:01
     ---------------------------------------- 11.3/11.3 MB 1.2 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Collecting numpy>=1.22.4
  Downloading numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)
     ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
     ---------------------------------------- 0.1/12.9 MB 1.1 MB/s eta 0:00:12
     ---------------------------------------- 0.1/12.9 MB 1.4 MB/s eta 0:00:10
      --------------------------------------- 0.2/12.9 MB 1.7 MB/s eta 0:00:08
     - -------------------------------------- 0.3/12.9 MB 1.8 MB/s eta 0:00:07
     - -------------------------------------- 0.4/12.9 MB 1.9 MB/s eta 0:00:07
     - -------------------------------------- 0.5/12.9 MB 1.9 MB/s eta 0:00:07
     - -------------------------------------- 0.6/12.9 MB 1.9 MB/s eta 0:00:07
     -- ------------------------------------- 0.7/12.9 MB 1.9 MB/s eta 0:00:07
     -- ------------------------------------- 0.8/12.9 MB 1.9 MB/s eta 0:00:07
     -- ------------------------------------- 0.9/12.9 MB 1.9 MB/s eta 0:00:07
     -- ------------------------------------- 0.9/12.9 MB 1.8 MB/s eta 0:00:07
     -- ------------------------------------- 1.0/12.9 MB 1.7 MB/s eta 0:00:07
     -- ------------------------------------- 1.0/12.9 MB 1.7 MB/s eta 0:00:07
     --- ------------------------------------ 1.1/12.9 MB 1.6 MB/s eta 0:00:08
     --- ------------------------------------ 1.1/12.9 MB 1.7 MB/s eta 0:00:08
     --- ------------------------------------ 1.2/12.9 MB 1.6 MB/s eta 0:00:08
     --- ------------------------------------ 1.3/12.9 MB 1.6 MB/s eta 0:00:08
     ---- ----------------------------------- 1.3/12.9 MB 1.6 MB/s eta 0:00:08
     ---- ----------------------------------- 1.4/12.9 MB 1.6 MB/s eta 0:00:08
     ---- ----------------------------------- 1.4/12.9 MB 1.5 MB/s eta 0:00:08
     ---- ----------------------------------- 1.5/12.9 MB 1.5 MB/s eta 0:00:08
     ---- ----------------------------------- 1.5/12.9 MB 1.5 MB/s eta 0:00:08
     ---- ----------------------------------- 1.6/12.9 MB 1.5 MB/s eta 0:00:08
     ----- ---------------------------------- 1.7/12.9 MB 1.5 MB/s eta 0:00:08
     ----- ---------------------------------- 1.7/12.9 MB 1.5 MB/s eta 0:00:08
     ----- ---------------------------------- 1.8/12.9 MB 1.5 MB/s eta 0:00:08
     ----- ---------------------------------- 1.8/12.9 MB 1.4 MB/s eta 0:00:08
     ----- ---------------------------------- 1.9/12.9 MB 1.4 MB/s eta 0:00:08
     ----- ---------------------------------- 1.9/12.9 MB 1.4 MB/s eta 0:00:08
     ------ --------------------------------- 2.0/12.9 MB 1.4 MB/s eta 0:00:08
     ------ --------------------------------- 2.1/12.9 MB 1.4 MB/s eta 0:00:08
     ------ --------------------------------- 2.1/12.9 MB 1.4 MB/s eta 0:00:08
     ------ --------------------------------- 2.2/12.9 MB 1.4 MB/s eta 0:00:08
     ------ --------------------------------- 2.2/12.9 MB 1.4 MB/s eta 0:00:08
     ------- -------------------------------- 2.3/12.9 MB 1.4 MB/s eta 0:00:08
     ------- -------------------------------- 2.3/12.9 MB 1.4 MB/s eta 0:00:08
     ------- -------------------------------- 2.4/12.9 MB 1.4 MB/s eta 0:00:08
     ------- -------------------------------- 2.4/12.9 MB 1.4 MB/s eta 0:00:08
     ------- -------------------------------- 2.5/12.9 MB 1.4 MB/s eta 0:00:08
     ------- -------------------------------- 2.6/12.9 MB 1.4 MB/s eta 0:00:08
     -------- ------------------------------- 2.6/12.9 MB 1.4 MB/s eta 0:00:08
     -------- ------------------------------- 2.7/12.9 MB 1.4 MB/s eta 0:00:08
     -------- ------------------------------- 2.7/12.9 MB 1.4 MB/s eta 0:00:08
     -------- ------------------------------- 2.8/12.9 MB 1.4 MB/s eta 0:00:08
     -------- ------------------------------- 2.8/12.9 MB 1.4 MB/s eta 0:00:08
     -------- ------------------------------- 2.9/12.9 MB 1.3 MB/s eta 0:00:08
     --------- ------------------------------ 3.0/12.9 MB 1.3 MB/s eta 0:00:08
     --------- ------------------------------ 3.0/12.9 MB 1.3 MB/s eta 0:00:08
     --------- ------------------------------ 3.1/12.9 MB 1.3 MB/s eta 0:00:08
     --------- ------------------------------ 3.1/12.9 MB 1.3 MB/s eta 0:00:08
     --------- ------------------------------ 3.2/12.9 MB 1.3 MB/s eta 0:00:08
     ---------- ----------------------------- 3.2/12.9 MB 1.3 MB/s eta 0:00:08

[notice] A new release of pip is available: 23.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
python.exe -m pip install --upgrade pip

SyntaxError: invalid syntax (842801469.py, line 1)

In [8]:
import pandas as pd

In [12]:
a = [1, 2, 3, 4]
b = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
df = pd.Series(a)

df

0    1
1    2
2    3
3    4
dtype: int64

In [14]:
df1 = pd.DataFrame(b)
df1

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [15]:
a = [["name", "age", "pro"],[10, 15, 20], ["hello", "hi", "bye"]]

In [16]:
pd.Series(a)

0    [name, age, pro]
1        [10, 15, 20]
2    [hello, hi, bye]
dtype: object

In [17]:
pd.DataFrame(a)

       0    1    2
0   name  age  pro
1     10   15   20
2  hello   hi  bye

In [18]:
a = [["python", 1989, "200k"],["c", 15, 20], ["java", "hi", "bye"]]
pd.DataFrame(a)

        0     1     2
0  python  1989  200k
1       c    15    20
2    java    hi   bye

In [20]:
a = [["python", 1989, "200k"],["c", 1930, "20k"], ["java", 1999, "30k"]]
pd.DataFrame(a, columns =["name", "year", "user"])

     name  year  user
0  python  1989  200k
1       c  1930   20k
2    java  1999   30k

In [23]:
dic

{'name': ['hello', 'Hi'],
 'age': [13, 12],
 'car': {'car_name': ['corola', 'toyota'], 'model': ['A', 'B']}}

In [24]:
pd.DataFrame(dic)

ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.

In [25]:
df = pd.DataFrame(a)
df

        0     1     2
0  python  1989  200k
1       c  1930   20k
2    java  1999   30k

In [30]:
df["user"] = [2000, 3000, 7]
df

        0     1     2  user
0  python  1989  200k  2000
1       c  1930   20k  3000
2    java  1999   30k     7

In [32]:
df['user']

0    2000
1    3000
2       7
Name: user, dtype: int64

In [33]:
df[['user']]

   user
0  2000
1  3000
2     7

In [36]:
dic_update = {"name" : 'react', "age" : [150], "year" : [2005], "user" : [1500] }
dic_update

{'name': 'react', 'age': [150], 'year': [2005], 'user': [1500]}

In [38]:
new_df = pd.DataFrame(dic_update)
new_df

    name  age  year  user
0  react  150  2005  1500

In [42]:
merge_df = pd.concat([df, new_df], ignore_index=True , axis=1)
merge_df

        0     1     2     3      4      5       6       7
0  python  1989  200k  2000  react  150.0  2005.0  1500.0
1       c  1930   20k  3000    NaN    NaN     NaN     NaN
2    java  1999   30k     7    NaN    NaN     NaN     NaN

In [1]:
import pandas as pd

a = [1, 2, 3, 4]

myvar = pd.Series(a)

print(myvar)

0    1
1    2
2    3
3    4
dtype: int64

In [2]:
print(myvar[0])

1

In [4]:
myvar2 = pd.Series(a, index= ['x','y', 'z', 's'])
print(myvar2)

x    1
y    2
z    3
s    4
dtype: int64