In [1]:
url = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'

In [ ]:
%pip install requests

Collecting requests
  Downloading requests-2.32.5-py3-none-any.whl (64 kB)
     ---------------------------------------- 0.0/64.7 kB ? eta -:--:--
     ------------------ --------------------- 30.7/64.7 kB 1.4 MB/s eta 0:00:01
     ------------------------------------ - 61.4/64.7 kB 656.4 kB/s eta 0:00:01
     -------------------------------------- 64.7/64.7 kB 586.0 kB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2026.1.4-py3-none-any.whl (152 kB)
     ---------------------------------------- 0.0/152.9 kB ? eta -:--:--
     ----------------------- --------------- 92.2/152.9 kB 2.6 MB/s eta 0:00:01
     -------------------------------------- 152.9/152.9 kB 1.8 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.11-py3-none-any.whl (71 kB)
     ---------------------------------------- 0.0/71.0 kB ? eta -:--:--
     ---------------------------------------- 71.0/71.0 kB 1.9 MB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
     ---------------------------------------- 0.0/131.6 kB ? eta -:--:--
     ------------------------ -------------- 81.9/131.6 kB 2.2 MB/s eta 0:00:01
     -------------------------------------- 131.6/131.6 kB 1.6 MB/s eta 0:00:00
Collecting charset_normalizer<4,>=2
  Downloading charset_normalizer-3.4.4-cp310-cp310-win_amd64.whl (107 kB)
     ---------------------------------------- 0.0/107.2 kB ? eta -:--:--
     -------------------------------------- 107.2/107.2 kB 3.1 MB/s eta 0:00:00
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests
Successfully installed certifi-2026.1.4 charset_normalizer-3.4.4 idna-3.11 requests-2.32.5 urllib3-2.6.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
%pip install --upgrade pip

Requirement already satisfied: pip in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (23.0.1)
Collecting pip
  Downloading pip-26.0-py3-none-any.whl (1.8 MB)
     ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
      --------------------------------------- 0.0/1.8 MB 1.4 MB/s eta 0:00:02
     -- ------------------------------------- 0.1/1.8 MB 1.3 MB/s eta 0:00:02
     ---- ----------------------------------- 0.2/1.8 MB 1.5 MB/s eta 0:00:02
     ------- -------------------------------- 0.3/1.8 MB 1.8 MB/s eta 0:00:01
     ---------- ----------------------------- 0.5/1.8 MB 2.2 MB/s eta 0:00:01
     ------------- -------------------------- 0.6/1.8 MB 2.4 MB/s eta 0:00:01
     ------------- -------------------------- 0.6/1.8 MB 2.3 MB/s eta 0:00:01
     ------------- -------------------------- 0.6/1.8 MB 2.3 MB/s eta 0:00:01
     --------------- ------------------------ 0.7/1.8 MB 1.7 MB/s eta 0:00:01
     ---------------- ----------------------- 0.7/1.8 MB 1.6 MB/s eta 0:00:01
     ----------------- ---------------------- 0.8/1.8 MB 1.6 MB/s eta 0:00:01
     ----------------- ---------------------- 0.8/1.8 MB 1.6 MB/s eta 0:00:01
     ----------------- ---------------------- 0.8/1.8 MB 1.4 MB/s eta 0:00:01
     ----------------- ---------------------- 0.8/1.8 MB 1.4 MB/s eta 0:00:01
     --------------------- ------------------ 1.0/1.8 MB 1.4 MB/s eta 0:00:01
     --------------------- ------------------ 1.0/1.8 MB 1.4 MB/s eta 0:00:01
     --------------------- ------------------ 1.0/1.8 MB 1.4 MB/s eta 0:00:01
     ------------------------ --------------- 1.1/1.8 MB 1.3 MB/s eta 0:00:01
     ------------------------ --------------- 1.1/1.8 MB 1.3 MB/s eta 0:00:01
     ------------------------ --------------- 1.1/1.8 MB 1.3 MB/s eta 0:00:01
     -------------------------------- ------- 1.5/1.8 MB 1.5 MB/s eta 0:00:01
     --------------------------------- ------ 1.5/1.8 MB 1.5 MB/s eta 0:00:01
     ---------------------------------- ----- 1.5/1.8 MB 1.5 MB/s eta 0:00:01
     ---------------------------------- ----- 1.5/1.8 MB 1.5 MB/s eta 0:00:01
     ---------------------------------- ----- 1.6/1.8 MB 1.3 MB/s eta 0:00:01
     ------------------------------------- -- 1.7/1.8 MB 1.4 MB/s eta 0:00:01
     ---------------------------------------  1.8/1.8 MB 1.4 MB/s eta 0:00:01
     ---------------------------------------- 1.8/1.8 MB 1.4 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.0.1
    Uninstalling pip-23.0.1:
      Successfully uninstalled pip-23.0.1
Successfully installed pip-26.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import requests
from io import StringIO

data = requests.get(url)
df = StringIO(data.text)

df1 = pd.read_csv(df)

df1.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [19]:
%pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.7.2-cp310-cp310-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.22.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (2.2.6)
Collecting scipy>=1.8.0 (from scikit-learn)
  Downloading scipy-1.15.3-cp310-cp310-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.7.2-cp310-cp310-win_amd64.whl (8.9 MB)
   ---------------------------------------- 0.0/8.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.9 MB 3.3 MB/s eta 0:00:03
   -- ------------------------------------- 0.5/8.9 MB 3.3 MB/s eta 0:00:03
   --- ------------------------------------ 0.8/8.9 MB 1.1 MB/s eta 0:00:08
   ---- ----------------------------------- 1.0/8.9 MB 1.2 MB/s eta 0:00:07
   ---- ----------------------------------- 1.0/8.9 MB 1.2 MB/s eta 0:00:07
   ------- -------------------------------- 1.6/8.9 MB 1.2 MB/s eta 0:00:07
   -------- ------------------------------- 1.8/8.9 MB 1.2 MB/s eta 0:00:06
   --------- ------------------------------ 2.1/8.9 MB 1.3 MB/s eta 0:00:06
   ---------- ----------------------------- 2.4/8.9 MB 1.3 MB/s eta 0:00:06
   ----------- ---------------------------- 2.6/8.9 MB 1.3 MB/s eta 0:00:05
   ------------ --------------------------- 2.9/8.9 MB 1.3 MB/s eta 0:00:05
   -------------- ------------------------- 3.1/8.9 MB 1.3 MB/s eta 0:00:05
   --------------- ------------------------ 3.4/8.9 MB 1.2 MB/s eta 0:00:05
   ---------------- ----------------------- 3.7/8.9 MB 1.3 MB/s eta 0:00:05
   ----------------- ---------------------- 3.9/8.9 MB 1.3 MB/s eta 0:00:04
   ------------------ --------------------- 4.2/8.9 MB 1.2 MB/s eta 0:00:04
   -------------------- ------------------- 4.5/8.9 MB 1.3 MB/s eta 0:00:04
   --------------------- ------------------ 4.7/8.9 MB 1.3 MB/s eta 0:00:04
   ---------------------- ----------------- 5.0/8.9 MB 1.3 MB/s eta 0:00:04
   ----------------------- ---------------- 5.2/8.9 MB 1.3 MB/s eta 0:00:03
   ----------------------- ---------------- 5.2/8.9 MB 1.3 MB/s eta 0:00:03
   ------------------------- -------------- 5.8/8.9 MB 1.2 MB/s eta 0:00:03
   --------------------------- ------------ 6.0/8.9 MB 1.2 MB/s eta 0:00:03
   ---------------------------- ----------- 6.3/8.9 MB 1.2 MB/s eta 0:00:03
   ----------------------------- ---------- 6.6/8.9 MB 1.2 MB/s eta 0:00:02
   ------------------------------ --------- 6.8/8.9 MB 1.2 MB/s eta 0:00:02
   ------------------------------- -------- 7.1/8.9 MB 1.2 MB/s eta 0:00:02
   --------------------------------- ------ 7.3/8.9 MB 1.2 MB/s eta 0:00:02
   ---------------------------------- ----- 7.6/8.9 MB 1.2 MB/s eta 0:00:02
   ----------------------------------- ---- 7.9/8.9 MB 1.2 MB/s eta 0:00:01
   ------------------------------------ --- 8.1/8.9 MB 1.2 MB/s eta 0:00:01
   ------------------------------------- -- 8.4/8.9 MB 1.2 MB/s eta 0:00:01
   -------------------------------------- - 8.7/8.9 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 8.9/8.9 MB 1.2 MB/s  0:00:07
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.15.3-cp310-cp310-win_amd64.whl (41.3 MB)
   ---------------------------------------- 0.0/41.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.3 MB ? eta -:--:--
    --------------------------------------- 0.5/41.3 MB 1.7 MB/s eta 0:00:25
    --------------------------------------- 0.8/41.3 MB 1.7 MB/s eta 0:00:25
   - -------------------------------------- 1.0/41.3 MB 1.5 MB/s eta 0:00:28
   - -------------------------------------- 1.3/41.3 MB 1.4 MB/s eta 0:00:28
   - -------------------------------------- 1.6/41.3 MB 1.4 MB/s eta 0:00:29
   - -------------------------------------- 1.6/41.3 MB 1.4 MB/s eta 0:00:29
   -- ------------------------------------- 2.1/41.3 MB 1.3 MB/s eta 0:00:32
   -- ------------------------------------- 2.4/41.3 MB 1.3 MB/s eta 0:00:30
   -- ------------------------------------- 2.6/41.3 MB 1.2 MB/s eta 0:00:32
   -- ------------------------------------- 2.9/41.3 MB 1.3 MB/s eta 0:00:30
   --- ------------------------------------ 3.1/41.3 MB 1.2 MB/s eta 0:00:31
   --- ------------------------------------ 3.4/41.3 MB 1.3 MB/s eta 0:00:30
   --- ------------------------------------ 3.7/41.3 MB 1.2 MB/s eta 0:00:31
   --- ------------------------------------ 3.9/41.3 MB 1.3 MB/s eta 0:00:30
   ---- ----------------------------------- 4.2/41.3 MB 1.2 MB/s eta 0:00:31
   ---- ----------------------------------- 4.5/41.3 MB 1.3 MB/s eta 0:00:30
   ---- ----------------------------------- 4.7/41.3 MB 1.3 MB/s eta 0:00:30
   ---- ----------------------------------- 5.0/41.3 MB 1.3 MB/s eta 0:00:29
   ----- ---------------------------------- 5.2/41.3 MB 1.3 MB/s eta 0:00:29
   ----- ---------------------------------- 5.5/41.3 MB 1.3 MB/s eta 0:00:29
   ----- ---------------------------------- 5.8/41.3 MB 1.2 MB/s eta 0:00:29
   ----- ---------------------------------- 6.0/41.3 MB 1.2 MB/s eta 0:00:29
   ------ --------------------------------- 6.3/41.3 MB 1.2 MB/s eta 0:00:29
   ------ --------------------------------- 6.6/41.3 MB 1.2 MB/s eta 0:00:28
   ------ --------------------------------- 6.8/41.3 MB 1.2 MB/s eta 0:00:28
   ------ --------------------------------- 7.1/41.3 MB 1.2 MB/s eta 0:00:28
   ------- -------------------------------- 7.3/41.3 MB 1.2 MB/s eta 0:00:28
   ------- -------------------------------- 7.6/41.3 MB 1.2 MB/s eta 0:00:28
   ------- -------------------------------- 7.9/41.3 MB 1.2 MB/s eta 0:00:27
   ------- -------------------------------- 8.1/41.3 MB 1.2 MB/s eta 0:00:27
   -------- ------------------------------- 8.4/41.3 MB 1.2 MB/s eta 0:00:27
   -------- ------------------------------- 8.4/41.3 MB 1.2 MB/s eta 0:00:27
   -------- ------------------------------- 8.7/41.3 MB 1.2 MB/s eta 0:00:27
   -------- ------------------------------- 8.9/41.3 MB 1.2 MB/s eta 0:00:27
   -------- ------------------------------- 9.2/41.3 MB 1.2 MB/s eta 0:00:26
   --------- ------------------------------ 9.4/41.3 MB 1.2 MB/s eta 0:00:26
   --------- ------------------------------ 9.7/41.3 MB 1.2 MB/s eta 0:00:26
   --------- ------------------------------ 10.0/41.3 MB 1.2 MB/s eta 0:00:26
   --------- ------------------------------ 10.2/41.3 MB 1.2 MB/s eta 0:00:26
   ---------- ----------------------------- 10.5/41.3 MB 1.2 MB/s eta 0:00:25
   ---------- ----------------------------- 10.7/41.3 MB 1.2 MB/s eta 0:00:25
   ---------- ----------------------------- 11.0/41.3 MB 1.2 MB/s eta 0:00:25
   ---------- ----------------------------- 11.3/41.3 MB 1.2 MB/s eta 0:00:25
   ----------- ---------------------------- 11.5/41.3 MB 1.2 MB/s eta 0:00:25
   ----------- ---------------------------- 11.8/41.3 MB 1.2 MB/s eta 0:00:24
   ----------- ---------------------------- 12.1/41.3 MB 1.2 MB/s eta 0:00:24
   ----------- ---------------------------- 12.3/41.3 MB 1.2 MB/s eta 0:00:24
   ------------ --------------------------- 12.6/41.3 MB 1.2 MB/s eta 0:00:24
   ------------ --------------------------- 12.8/41.3 MB 1.2 MB/s eta 0:00:24
   ------------ --------------------------- 13.1/41.3 MB 1.2 MB/s eta 0:00:23
   ------------ --------------------------- 13.4/41.3 MB 1.2 MB/s eta 0:00:23
   ------------- -------------------------- 13.6/41.3 MB 1.2 MB/s eta 0:00:23
   ------------- -------------------------- 13.9/41.3 MB 1.2 MB/s eta 0:00:23
   ------------- -------------------------- 14.2/41.3 MB 1.2 MB/s eta 0:00:23
   ------------- -------------------------- 14.4/41.3 MB 1.2 MB/s eta 0:00:22
   -------------- ------------------------- 14.7/41.3 MB 1.2 MB/s eta 0:00:22
   -------------- ------------------------- 14.9/41.3 MB 1.2 MB/s eta 0:00:22
   -------------- ------------------------- 15.2/41.3 MB 1.2 MB/s eta 0:00:22
   -------------- ------------------------- 15.5/41.3 MB 1.2 MB/s eta 0:00:22
   --------------- ------------------------ 15.7/41.3 MB 1.2 MB/s eta 0:00:21
   --------------- ------------------------ 16.0/41.3 MB 1.2 MB/s eta 0:00:21
   --------------- ------------------------ 16.3/41.3 MB 1.2 MB/s eta 0:00:21
   ---------------- ----------------------- 16.5/41.3 MB 1.2 MB/s eta 0:00:21
   ---------------- ----------------------- 16.8/41.3 MB 1.2 MB/s eta 0:00:20
   ---------------- ----------------------- 17.0/41.3 MB 1.2 MB/s eta 0:00:20
   ---------------- ----------------------- 17.3/41.3 MB 1.2 MB/s eta 0:00:20
   ----------------- ---------------------- 17.6/41.3 MB 1.2 MB/s eta 0:00:20
   ----------------- ---------------------- 17.8/41.3 MB 1.2 MB/s eta 0:00:20
   ----------------- ---------------------- 18.1/41.3 MB 1.2 MB/s eta 0:00:19
   ----------------- ---------------------- 18.4/41.3 MB 1.2 MB/s eta 0:00:19
   ------------------ --------------------- 18.6/41.3 MB 1.2 MB/s eta 0:00:19
   ------------------ --------------------- 18.9/41.3 MB 1.2 MB/s eta 0:00:19
   ------------------ --------------------- 19.1/41.3 MB 1.2 MB/s eta 0:00:19
   ------------------ --------------------- 19.4/41.3 MB 1.2 MB/s eta 0:00:18
   ------------------- -------------------- 19.7/41.3 MB 1.2 MB/s eta 0:00:18
   ------------------- -------------------- 19.9/41.3 MB 1.2 MB/s eta 0:00:18
   ------------------- -------------------- 20.2/41.3 MB 1.2 MB/s eta 0:00:18
   ------------------- -------------------- 20.4/41.3 MB 1.2 MB/s eta 0:00:18
   -------------------- ------------------- 20.7/41.3 MB 1.2 MB/s eta 0:00:17
   -------------------- ------------------- 21.0/41.3 MB 1.2 MB/s eta 0:00:17
   -------------------- ------------------- 21.2/41.3 MB 1.2 MB/s eta 0:00:17
   -------------------- ------------------- 21.5/41.3 MB 1.2 MB/s eta 0:00:17
   --------------------- ------------------ 21.8/41.3 MB 1.2 MB/s eta 0:00:16
   --------------------- ------------------ 22.0/41.3 MB 1.2 MB/s eta 0:00:16
   --------------------- ------------------ 22.3/41.3 MB 1.2 MB/s eta 0:00:16
   --------------------- ------------------ 22.5/41.3 MB 1.2 MB/s eta 0:00:16
   ---------------------- ----------------- 22.8/41.3 MB 1.2 MB/s eta 0:00:16
   ---------------------- ----------------- 23.1/41.3 MB 1.2 MB/s eta 0:00:15
   ---------------------- ----------------- 23.3/41.3 MB 1.2 MB/s eta 0:00:15
   ---------------------- ----------------- 23.3/41.3 MB 1.2 MB/s eta 0:00:15
   ----------------------- ---------------- 23.9/41.3 MB 1.2 MB/s eta 0:00:15
   ----------------------- ---------------- 24.1/41.3 MB 1.2 MB/s eta 0:00:15
   ----------------------- ---------------- 24.4/41.3 MB 1.2 MB/s eta 0:00:14
   ----------------------- ---------------- 24.6/41.3 MB 1.2 MB/s eta 0:00:14
   ------------------------ --------------- 24.9/41.3 MB 1.2 MB/s eta 0:00:14
   ------------------------ --------------- 25.2/41.3 MB 1.2 MB/s eta 0:00:14
   ------------------------ --------------- 25.4/41.3 MB 1.2 MB/s eta 0:00:13
   ------------------------ --------------- 25.7/41.3 MB 1.2 MB/s eta 0:00:13
   ------------------------ --------------- 25.7/41.3 MB 1.2 MB/s eta 0:00:13
   ------------------------- -------------- 26.0/41.3 MB 1.2 MB/s eta 0:00:13
   ------------------------- -------------- 26.2/41.3 MB 1.2 MB/s eta 0:00:13
   ------------------------- -------------- 26.5/41.3 MB 1.2 MB/s eta 0:00:13
   ------------------------- -------------- 26.7/41.3 MB 1.2 MB/s eta 0:00:12
   -------------------------- ------------- 27.0/41.3 MB 1.2 MB/s eta 0:00:12
   -------------------------- ------------- 27.3/41.3 MB 1.2 MB/s eta 0:00:12
   -------------------------- ------------- 27.5/41.3 MB 1.2 MB/s eta 0:00:12
   -------------------------- ------------- 27.8/41.3 MB 1.2 MB/s eta 0:00:12
   --------------------------- ------------ 28.0/41.3 MB 1.2 MB/s eta 0:00:11
   --------------------------- ------------ 28.3/41.3 MB 1.2 MB/s eta 0:00:11
   --------------------------- ------------ 28.6/41.3 MB 1.2 MB/s eta 0:00:11
   --------------------------- ------------ 28.8/41.3 MB 1.2 MB/s eta 0:00:11
   ---------------------------- ----------- 29.1/41.3 MB 1.2 MB/s eta 0:00:10
   ---------------------------- ----------- 29.4/41.3 MB 1.2 MB/s eta 0:00:10
   ---------------------------- ----------- 29.6/41.3 MB 1.2 MB/s eta 0:00:10
   ---------------------------- ----------- 29.9/41.3 MB 1.2 MB/s eta 0:00:10
   ----------------------------- ---------- 30.1/41.3 MB 1.2 MB/s eta 0:00:10
   ----------------------------- ---------- 30.4/41.3 MB 1.2 MB/s eta 0:00:09
   ----------------------------- ---------- 30.7/41.3 MB 1.2 MB/s eta 0:00:09
   ----------------------------- ---------- 30.9/41.3 MB 1.2 MB/s eta 0:00:09
   ------------------------------ --------- 31.2/41.3 MB 1.2 MB/s eta 0:00:09
   ------------------------------ --------- 31.5/41.3 MB 1.2 MB/s eta 0:00:09
   ------------------------------ --------- 31.7/41.3 MB 1.2 MB/s eta 0:00:08
   ------------------------------- -------- 32.0/41.3 MB 1.2 MB/s eta 0:00:08
   ------------------------------- -------- 32.2/41.3 MB 1.2 MB/s eta 0:00:08
   ------------------------------- -------- 32.5/41.3 MB 1.2 MB/s eta 0:00:08
   ------------------------------- -------- 32.8/41.3 MB 1.2 MB/s eta 0:00:07
   -------------------------------- ------- 33.0/41.3 MB 1.2 MB/s eta 0:00:07
   -------------------------------- ------- 33.3/41.3 MB 1.2 MB/s eta 0:00:07
   -------------------------------- ------- 33.6/41.3 MB 1.2 MB/s eta 0:00:07
   -------------------------------- ------- 33.8/41.3 MB 1.2 MB/s eta 0:00:07
   -------------------------------- ------- 33.8/41.3 MB 1.2 MB/s eta 0:00:07
   --------------------------------- ------ 34.3/41.3 MB 1.2 MB/s eta 0:00:06
   --------------------------------- ------ 34.6/41.3 MB 1.2 MB/s eta 0:00:06
   --------------------------------- ------ 34.9/41.3 MB 1.2 MB/s eta 0:00:06
   ---------------------------------- ----- 35.1/41.3 MB 1.2 MB/s eta 0:00:06
   ---------------------------------- ----- 35.4/41.3 MB 1.2 MB/s eta 0:00:05
   ---------------------------------- ----- 35.7/41.3 MB 1.2 MB/s eta 0:00:05
   ---------------------------------- ----- 35.9/41.3 MB 1.2 MB/s eta 0:00:05
   ----------------------------------- ---- 36.2/41.3 MB 1.2 MB/s eta 0:00:05
   ----------------------------------- ---- 36.4/41.3 MB 1.2 MB/s eta 0:00:04
   ----------------------------------- ---- 36.7/41.3 MB 1.2 MB/s eta 0:00:04
   ----------------------------------- ---- 37.0/41.3 MB 1.2 MB/s eta 0:00:04
   ------------------------------------ --- 37.2/41.3 MB 1.2 MB/s eta 0:00:04
   ------------------------------------ --- 37.5/41.3 MB 1.2 MB/s eta 0:00:04
   ------------------------------------ --- 37.7/41.3 MB 1.2 MB/s eta 0:00:03
   ------------------------------------ --- 38.0/41.3 MB 1.2 MB/s eta 0:00:03
   ------------------------------------- -- 38.3/41.3 MB 1.2 MB/s eta 0:00:03
   ------------------------------------- -- 38.5/41.3 MB 1.2 MB/s eta 0:00:03
   ------------------------------------- -- 38.8/41.3 MB 1.2 MB/s eta 0:00:03
   ------------------------------------- -- 39.1/41.3 MB 1.2 MB/s eta 0:00:02
   -------------------------------------- - 39.3/41.3 MB 1.2 MB/s eta 0:00:02
   -------------------------------------- - 39.6/41.3 MB 1.2 MB/s eta 0:00:02
   -------------------------------------- - 39.8/41.3 MB 1.2 MB/s eta 0:00:02
   -------------------------------------- - 40.1/41.3 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------  40.4/41.3 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------  40.4/41.3 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------  40.6/41.3 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------  40.9/41.3 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 41.3/41.3 MB 1.2 MB/s  0:00:33
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import seaborn as sns # dataset loader

le = LabelEncoder()

df = sns.load_dataset('titanic')

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
clf = LogisticRegression(max_iter=200)
clf.fit(X_train, y_train)
pred = clf.predict(X_test)
print('Accuracy:', accuracy_score(y_test, pred))

Accuracy: 1.0